### ISSUE TITLE
[Mac] Error when launching with Java 9 or 10

### ISSUE THREAD

**Issue by tofi86** [paginagmbh/EPUB-Checker#38]
Java 9-ea seems to have problems with JNI methods:

```
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: com/apple/eawt/QuitHandler
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Unknown Source)
	at java.base/java.lang.Class.getMethodsRecursive(Unknown Source)
	at java.base/java.lang.Class.getMethod0(Unknown Source)
	at java.base/java.lang.Class.getMethod(Unknown Source)
	at java.base/sun.launcher.LauncherHelper.validateMainClass(Unknown Source)
	at java.base/sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
Caused by: java.lang.ClassNotFoundException: com.apple.eawt.QuitHandler
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 7 more
```

Tested with new `universalJavaApplicationStub` with Java 9 support (https://github.com/tofi86/universalJavaApplicationStub/issues/43).

However, `com/apple/eawt/QuitHandler` class is part of the EPUB-Checker-JAR...

**Comment by tofi86** [comment]
*(refs https://github.com/liamsharp/universalJavaApplicationStubDemo/issues/2)*

The apple specific event handlers do not work with Java 9 anymore because Java 9 deprecated/removed the classes from package `com.apple.eawt.*`. See the following links for details:
* https://docs.oracle.com/javase/9/migrate/toc.htm#JSMIG-GUID-97C1D0BB-D5D3-4CAD-B17D-03A87A0AAF3B
* http://openjdk.java.net/jeps/272

People came up with workarounds, like Reflection:
* https://gist.github.com/ctipper/678268819df75b366b34e78ff413bb3a
* https://github.com/SubOptimal/keystore-explorer/blob/master/kse/src/org/kse/gui/MacOsIntegration.java

**Comment by tofi86** [comment]
The Mac launcher script can work with Java 9, the Windows launcher not yet. However:

Launch4j 3.12 was released with support for Java 9 and 10: http://launch4j.sourceforge.net/changelog.html

Waiting for an update of the maven launch4j plugin https://github.com/lukaszlenart/launch4j-maven-plugin/issues/75 and then we can try again.

**Comment by tofi86** [comment]
Windows launcher supports Java 9 and 10 now, works as expected.
